### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by Godzil**
I'm currently looking how you have generated the PDFs files, and haven't changed the EN and DE index to add a link to the French version. I will update my branch shortly with that.

### CODE REVIEW

**Comment by ztiromoritz** [comment]
First of all: Merci! Awesome to have a french translation.
I used no script to generate the pdf, just "Print to PDF" in Chrome.

**Comment by Godzil** [comment]
That's nothing :smiley: I will ask some friends to proofread to be sure there is no blatant mistake I haven’t saw. (there are some term which are quite hard to translate in French as we tend to use the English word... :smile:)

**Comment by Godzil** [comment]
I've made a slight change in the Cheatsheet, The Ctrl+R shortcut was missing, I've added in the french version and bumped the version to 2.1, I will update both German and English version once I've finished proofreading with the French version if you accept this change (I needed to do a small tweak in the CSS to not break the current presentation)

**Comment by Godzil** [comment]
Ok some more commit on my side, I've updated the DE and EN version to match the changes in the French version.

The changes are:
- External CSS (easier to get the same on all pages)
- Added link in EN/DE pages to the French version (and to the PDF)
- added CSS class to "overlay" the words in the music explanation image, not perfect, but works fine!
- updated version to 2.1 on each pages
- Added the Ctrl(STR)+R shortcut to EN and DE page (sorry if I chose the wrong word in german, I haven't done german for years)

~~The CSS file is not correctly clean (it is still shifted to the right, but I don't have proper tool to do that right now)~~ Done

**Comment by ztiromoritz** [comment]
Good idea to have a separated css-file. 
But there was a difference between the en and the de version to get A4 respectively US-Letter Format.  I would suggest we need a .page_us and .page_a4 class.

**Comment by ztiromoritz** [comment]
Diff between en and de css part. Not sure if all of this changes are really needed. The lesser the special cases the better i think. 

<pre>
         .page {
             font-family: Courier, monospace;
-            height: 297mm;
+            height: 277mm;
             width: 210mm;
             margin: 0 auto;
             background-color: #fff;
         }
         .title {
             width: 205mm;
-            height: 3mm;
+            height: 1mm;
             margin: 2.5mm;
             padding-top: 3mm;
             font-family: pico8, monospace;
+            font-size: 10px;
             /*background-color: #00ff00;*/
         }
         .block {
             width: 100%;
             background-color: #eee;
-            margin-top: 3mm;
-            margin-bottom: 3mm;
+            margin-top: 1mm;
+            margin-bottom: 0mm;
             background-color: #eee;
         }
         .block h3 {
-            margin-top: 3mm;
+            margin-top: 1mm;
             margin-left: 1mm;
             margin-bottom: 1mm;
         }
         code {
             font-family: pico8, monospace;
             line-height: 1.4;
-            font-size: 12px;
+            font-size: 11px;
         }
         p {
-            font-size: 13px;
+            font-size: 11px;
         }
</pre>

**Comment by ztiromoritz** [comment]
Let me know if you would like to do sth. else in this branch. Otherwise i would merge this one here.
(I could handle the US-Letter/A4 thing myself.)

**Comment by Godzil** [comment]
It is in a state I'm happy with! 

So I'll leave the merge to you, you are not obligated to accept all of my changes of course! :)

**Comment by Godzil** [comment]
Oh I missed your comment the A4/Letter part, and also in the code, sorry about that, yeah I suppose we can have two css for the page definition and include the one we want in each versions, sounds reasonable !

I suppose some differences come from the version 1 to version 2 changes?

**Comment by ztiromoritz** [comment]
Not sure where the changes come from. Anyway. The english version currently fits in A4 and in letter as well. So leave it like that. If we get more translations, it could be worth thinking about a simple i18n solution with language bundles.

**Pull request merged**
